theme: jekyll-theme-cayman
<html>
  <title>
    COUNTDOWN
  </title>
  <body>
    <h1> I miss you babe with all my heart </h1>
  </body>
  
  <style>
    body{ 
      color:#fff;
      text-align:center;
    }
  </style>
  
</html>
